# Generated by Django 4.2.7 on 2023-11-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='images/artist/')),
                ('year', models.PositiveSmallIntegerField(default=1994)),
                ('address', models.CharField(max_length=160)),
                ('phone', models.CharField(default='+998', max_length=24)),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Artist',
                'db_table': 'Artist',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_image', models.ImageField(blank=True, null=True, upload_to='images/song/')),
                ('music', models.FileField(upload_to='music/song/')),
                ('title', models.CharField(max_length=90)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('hip hop', 'Hip Hop'), ('rock', 'Rock'), ('soul', 'Soul'), ('country', 'Country'), ('folk', 'Folk'), ('jazz', 'Jazz'), ('disco', 'Disco'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('music for children', 'Music For Children')], max_length=50)),
                ('song_year', models.PositiveSmallIntegerField()),
                ('song_rate', models.CharField(choices=[('very bad', '⭐'), ('bad', '⭐⭐'), ('not bad', '⭐⭐⭐'), ('good', '⭐⭐⭐⭐'), ('very good', '⭐⭐⭐⭐⭐')], max_length=18)),
                ('sending_date', models.DateTimeField(auto_now=True)),
                ('song_time', models.CharField(blank=True, default='3:14', max_length=110, null=True)),
                ('listened', models.PositiveSmallIntegerField(default=0)),
                ('artist', models.ManyToManyField(to='song.artist')),
            ],
            options={
                'verbose_name_plural': 'Song',
                'db_table': 'Song',
                'ordering': ('song_year',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('album_image', models.ImageField(blank=True, null=True, upload_to='images/album/')),
                ('album_about', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.artist')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
            options={
                'verbose_name_plural': 'Album',
                'db_table': 'Album',
                'ordering': ('-views',),
            },
        ),
    ]
