# Generated by Django 4.2.7 on 2023-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-views',), 'verbose_name_plural': "Albo'mlar"},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('year',), 'verbose_name_plural': "Qo'shiqchilar"},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('song_year',), 'verbose_name_plural': "Qo'shiqlar"},
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, to='song.artist'),
        ),
    ]
